on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: |
          pnpm install

      - name: Typecheck
        run: |
          pnpm typecheck

      - name: Run tests
        run: |
          pnpm test
