on:
  workflow_dispatch:
  workflow_run:
    workflows: CI
    types:
      - completed

name: Deploy to Oracle Cloud

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: OCI
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_PRIVATE_KEY }}
          script: |
            export PATH=/home/ubuntu/n/bin:$PATH
            cd hogwarts-productivity-hub-bot && 
            git pull &&
            pnpm install &&
            pnpm register &&
            npx drizzle-kit migrate &&
            systemctl --user restart discord-bot.service
